services:
  rumahpc-postgres:
    image: postgres
    container_name: rumahpc-postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rumahpc_db
    volumes:
      - my_data:/var/lib/postgresql/data
  rumahpc-backend:
    build: .
    ports:
      - 8081:8080
    environment:
      - DB_HOST=rumahpc-postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=rumahpc_db
    depends_on:
      - rumahpc-postgres

volumes:
  my_data: